{{- if .Values.benji.argoWorkflows.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ tuple . "" | include "benji.fullname" }}
  labels:
    app.kubernetes.io/name: {{ include "benji.name" . }}
    helm.sh/chart: {{ include "benji.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - workflowtaskresults
    verbs:
      - create
      - patch
{{- end }}
