{{- if .Values.benji.argoWorkflows.enabled -}}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ tuple . "" | include "benji.fullname" }}
  labels:
    app.kubernetes.io/name: {{ include "benji.name" . }}
    helm.sh/chart: {{ include "benji.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ tuple . "" | include "benji.fullname" }}
subjects:
  - kind: ServiceAccount
    name: {{ tuple . "" | include "benji.fullname" }}
{{- end }}
